apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZ2hjci5pbyI6IHsiYXV0aCI6ICJhWE50YjJsc2JHMXBjbUZpWW05emIyWm1PbWRvY0Y5RVdYRlBiRmM1WkdsSk5YVkZUVXRIUldGQ2JITTBja3RPTURaVU4yd3hSSGhJYURFPSJ9fX0=


---
apiVersion: v1
kind: Secret
metadata:
  name: discovery
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: git@github.com:ismoillmirabbosoff/ArgoCD.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACB9dGpAjGGeBzCUefKexVoauiBRrjq0hLif35Gmgf7J3QAAAKBTxoLYU8aC
    2AAAAAtzc2gtZWQyNTUxOQAAACB9dGpAjGGeBzCUefKexVoauiBRrjq0hLif35Gmgf7J3Q
    AAAEBfmulE+Qcj3Wi52uySiV1KeFFdPKDrEEuvEYTHU7GWRX10akCMYZ4HMJR58p7FWhq6
    IFGuOrSEuJ/fkaaB/sndAAAAHGlzbW9pbGxtaXJhYmJvc29mZkBnbWFpbC5jb20B
    -----END OPENSSH PRIVATE KEY-----


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discovery
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ismoillmirabbosoff/ArgoCD.git
    targetRevision: HEAD
    path: .github/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    retry:
      limit: 2
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - Replace=true


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
    - shopnest.uz
    secretName: letsencrypt-prod
  rules:
  - host: shopnest.uz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ezzydocs
            port:
              number: 3000
